name: venezia
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.5
  - matplotlib
  - geopandas
  - earthpy
  - notebook==6.0.1
  - pandas
  - numpy
  - scikit-learn
  - seaborn
  - pulp
  - ipython
  - ipykernel

